In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 0.04508565  0.485636    0.70180343 -0.46522092 -0.08923   ]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[ 0.04508565  0.485636    0.70180343 -0.46522092 -0.08923   ]


In [4]:
print(np.dot(a,a.T))

0.954795592563


In [5]:
a = np.random.randn(5,1)

In [6]:
print(a)

[[ 1.40569478]
 [ 1.40051873]
 [-0.72796456]
 [-0.26020118]
 [-0.59913637]]


In [7]:
print(a.T)

[[ 1.40569478  1.40051873 -0.72796456 -0.26020118 -0.59913637]]


In [8]:
print(np.dot(a,a.T))

[[ 1.97597781  1.96870186 -1.02329598 -0.36576343 -0.84220287]
 [ 1.96870186  1.96145271 -1.019528   -0.36441662 -0.83910171]
 [-1.02329598 -1.019528    0.5299324   0.18941723  0.43615004]
 [-0.36576343 -0.36441662  0.18941723  0.06770465  0.15589599]
 [-0.84220287 -0.83910171  0.43615004  0.15589599  0.35896439]]


In [12]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [10]:
c.shape

(2, 3)

In [11]:
d = a*b
print(d)

[[-0.22203404  0.06294635  0.21195754]
 [-0.13026693 -1.19325523 -0.57764448]]


In [13]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a*b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [14]:
c.shape

(2, 3)

In [15]:
b.shape

(3, 2)

In [16]:
a.shape

(4, 3)

In [17]:
c = np.dot(a,b)
print(c)

[[ 0.36783044 -0.1909681 ]
 [-1.02899938 -0.86735542]
 [ 0.3163417   0.32189154]
 [ 2.6579443   0.78922739]]


In [18]:
c.shapehttp://localhost:8888/tree

SyntaxError: invalid syntax (<ipython-input-18-6fc3abdb4e5c>, line 1)

In [19]:
c.shape

(4, 2)

In [20]:
c = a.B + 10

AttributeError: 'numpy.ndarray' object has no attribute 'B'

In [21]:
c = a.b + 10

AttributeError: 'numpy.ndarray' object has no attribute 'b'

In [22]:
c = np.dot(a,b) + 10

In [23]:
print(c)

[[ 10.36783044   9.8090319 ]
 [  8.97100062   9.13264458]
 [ 10.3163417   10.32189154]
 [ 12.6579443   10.78922739]]


In [24]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a * b
c.shape

(3, 3)

In [25]:
print(c)

[[-0.05478431  0.1485953  -0.0107318 ]
 [ 0.43471904 -0.17589012  0.11521129]
 [ 0.69582024  0.75102912  0.61726274]]


In [27]:
a = [10, 2, 3]
b = ([3,2,5])
p = a * b
print (p)

TypeError: can't multiply sequence by non-int of type 'list'

In [37]:
image = np.array([[[1,2],
                  [2,3],
                  [4,5]],
                 
                 [[3,4],
                 [5,2],
                 [5,1]],
                  
                  [[1,3],
                  [1,1],
                  [2,2]]])
image.shape[0]

3

In [39]:
image[0][0].shape[0]

2

In [40]:
image[0].shape[0]

3

In [32]:
image[0].shape[1]

IndexError: tuple index out of range

In [34]:
image[1].shape[0]

3

In [35]:
print(image[0])

[[1, 2] [2.3] [4, 5]]


In [36]:
print (image[0][1])

[2.3]


In [41]:
image.shape[0]

3

In [48]:
x = np.array([[0,3,4],
             [1,6,4]])
x_norm = np.linalg.norm(x, axis=1, keepdims=True)
print(x_norm)

TypeError: norm() got an unexpected keyword argument 'keepdims'